### ISSUE TITLE
Medium speed not being highlighted when medPercentage is 50

### ISSUE THREAD

**Issue by heschlie** [finity69x2/fan-percent-button-row#19]
First, my config:

```yaml
type: entities
entities:
  - entity: fan.office_ceiling_fan_2
    type: custom:fan-percent-button-row
    customTheme: false
    lowPercentage: 25
    medPercentage: 50
    hiPercentage: 100
    reverseButtons: true
```

So, everything actually works, when I click any of the buttons the fan changes to the corresponding speed, but when I click MED the fan speed changes but the button isn't highlighted. If I click any of the others the corresponding button is highlighted. If I change `medPercentage` to 51, it seems to start working, so I'm wondering if what is being reported back by HA might not be exactly what this is watching for or something?
