### ISSUE TITLE
Fan speed is set to fixed values, even CustomSetpoints are used

### ISSUE THREAD

**Issue by skipper22hassio** [finity69x2/fan-percent-button-row#21]
Hi, 

when I press the High, Med, Low Butttons the speed is set to 100, 66, 33 respectively, even I've activated and defined custom Setpoints. What am I missing? 

```
type: entities
entities:
  - entity: fan.airflow_remote_control
    type: custom:fan-percent-button-row
    name: Airflow Power
    customTheme: false
    sendStateWithSpeed: true
    customSetpoints: true
    lowPercent: 50
    medPercent: 60
    hiPercent: 95
  - entity: input_boolean.fan_auto
```
Pressing the Low button sets the speed to 33%, not 50% as expected. 
```
speed_list:
  - 'off'
  - low
  - medium
  - high
preset_modes: []
speed: medium
percentage: 33
percentage_step: 1
preset_mode: null
friendly_name: Airflow Remote Control
supported_features: 1
```
Setting the fan speed to the developer tools works
```
service: fan.set_percentage
data:
  percentage: 53
target:
  entity_id: fan.airflow_remote_control
```

The state attributes in developer Tools then look like this: 
```
speed_list:
  - 'off'
  - low
  - medium
  - high
preset_modes: []
speed: medium
percentage: 53
percentage_step: 1
preset_mode: null
friendly_name: Airflow Remote Control
supported_features: 1
```

Here is my ESBHome setting for the fan control
```
Output variable
output:
  - platform: esp8266_pwm
    pin: D7
    frequency: 600 Hz
    id: fan_control_1
fan:
  - platform: speed
    output: fan_control_1
    name: "Airflow Remote Control"
    speed_count: 100
```

Running HA Core 2021.11.1
