### ISSUE TITLE
Off doesn't turn fan off

### ISSUE THREAD

**Issue by broyuken** [finity69x2/fan-percent-button-row#4]
Using the off button it doesn't turn the fan off, it just changes the speed. My fan uses a different IR code for on/off and change speed. Can you make the off button actually send the off command?

**Comment by febalci** [comment]
For sonoff ifan03, i face the same problem. Even tough the speed is 0 when i press the OFF button, the on/off switch is still ON.

**Comment by finity69x2** [comment]
Yes, I'll look into it.

I've just now mostly figured out how these new fan control changes are supposed to work.

**Comment by broyuken** [comment]
Appreciate it, this change to fans in HA is annoying but in the end I think it will be helpful overall.

**Comment by finity69x2** [comment]
I just made a change to the code.

Could you try it with the latest and see if it works OK now?

remember to clear the cache to force the new code to be reloaded after you restart HA.

**Comment by finity69x2** [comment]
> in the end I think it will be helpful overall.

Unfortunately I'm not as optimistic as you are.

I think they could have left the speed list stuff intact and just added the percentage stuff for people who needed it. It would have been way easier than trying to figure out how to transition to the new stuff for people who's fans were already working perfectly fine.

But that's water under the bridge now.

**Comment by broyuken** [comment]
Turning it off works as expected now, however if the fan is off and I click one of the speeds, nothing happens. The fan doesn't turn on.

**Comment by Stupco** [comment]
I also had the same issue with OFF not working, thought it was my code so didn't raise an issue.

Confirmed it kind of works in v1.3 (better than before), however after it turns off, 3 seconds later is is turned back on automatically.

My code as follows:

```
#CONFIGURATION
fan:
  - platform: template
    fans:
      b3_fan:
        friendly_name: "Bedroom 3 Fan"
        value_template: "{{ states('input_boolean.b3_fan_state') }}"
        percentage_template: "{{ states('input_select.b3_fan_speed') }}"
        turn_on:
          service: script.fan_on
        turn_off:
          service: script.fan_off
        set_percentage:
          service: script.fan_set_speed
          data:
            percentage: "{{ percentage }}"
            name: "b3"

#SCRIPT
fan_off:
  alias: Fan Off
  sequence:
    - service: remote.send_command
      data:
        entity_id: remote.rmpro_remote
        command: b64:sgDKAAsXCxcLChgXChcLChgKGAoYChgKGAoYChcKGAsXChgKGBcLFwoYCgsXFwsXCwoXFwsKGBcKCxcLFwoYChgKGAABCAwXCxcKGAoLFxcKFwsLFwoYChgKGAoYChgKGAoYChgKGAoXFwsXCxcLChgWDBYLChgXCwoXFwsKFwsXChgKFwsYAAEIDBYLFwsXCgsXFwsXCwoYChgKGAoXCxcKGQoXChgKGAoYChgXChgKFwsLFxcLFwoLFxcLChcXCwoYChcLFwoYCxcABdwAAAAAAAAAAAAAAAAAAA==
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.b3_fan_state
```

Two things additional to this issue:

1. Can you have it so that the state can still be called even if it is currently selected (ie. Let me call the OFF service, even if Fan Percent Button Row thinks the fan is OFF)?
2. When will this be available on HACS? :)
