### ISSUE TITLE
NOOB

### ISSUE THREAD

**Issue by montyfox** [finity69x2/fan-percent-button-row#9]
I have confirmed that I've installed and can see it in the lovelace resources.  However, I am unable to get this to work at all.  What card type do you start with?  I've tried the entity card and filled in the example yaml code and replaced with my device's entity name. Still nothing.  I know I'm new to this, but everything assumes you are already familiar with all aspects of yaml and home assisant.  I'd really appreciate a simple walk through of setting up a 3 speed fan control using percentages with this add on.  Thanks

**Comment by finity69x2** [comment]
> I am unable to get this to work at all.

Can you be more specific?

Are you seeing a red screen where the plugin should be?

Do you have the control row visible but it isn't controlling your fan?

Do you have your fan set up to actually use the percent control model in HA?

**Comment by Godis1coolguy** [comment]
I have a red screen where the plugin should be with the error "Custom element doesn't exist: fan-percent-button-row." I installed through HACS.

My code looks like this. I'm not sure why the quotes keep getting added to the beginning and end of my type line. They aren't there when I save it, but show up again after it gives me the error.

```
  - title: Inside
    path: inside
    theme: Caule Black Purple Glass
    badges: []
    cards:
      - type: entities
        title: Den Fan
        show_header_toggle: false
        entities:
          - entity: fan.den_fan
            type: 'custom:fan-percent-button-row'
            name: Fan Not Custom Theme
            customTheme: false
```
